export const tree = [
  {
    title: '知识单元',
    key: '1',
    scopedSlots: { title: 'custom' },
    children: [
      {
        title: '1+X',
        name: '1+X',
        key: '1-1',
        scopedSlots: { title: 'custom' },
        children: [
          {
            title: '初级',
            name: '初级',
            key: '1-1-1',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-1',
          },
          {
            title: '中级',
            name: '中级',
            key: '1-1-2',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-1',
          },
          {
            title: '高级',
            name: '高级',
            key: '1-1-3',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-1',
          },
        ],
      },
      {
        title: '中职国赛',
        name: '中职国赛',
        key: '1-2',
        scopedSlots: { title: 'custom' },
        children: [
          {
            title: '建筑工程测量基础知识',
            name: '建筑工程测量基础知识',
            key: '1-2-1',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
          {
            title: '角度测量',
            name: '角度测量',
            key: '1-2-2',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
          {
            title: '距离测量与直线定向',
            name: '距离测量与直线定向',
            key: '1-2-3',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
          {
            title: '测量误差的基本知识',
            name: '测量误差的基本知识',
            key: '1-2-4',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
          {
            title: '平面控制测量',
            name: '平面控制测量',
            key: '1-2-5',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
          {
            title: '地形图的基本知识',
            name: '地形图的基本知识',
            key: '1-2-6',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
          {
            title: '施工测量',
            name: '施工测量',
            key: '1-2-7',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
          {
            title: '全站仪测量',
            name: '全站仪测量',
            key: '1-2-8',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
          {
            title: '水准测量',
            name: '水准测量',
            key: '1-2-9',
            scopedSlots: { title: 'custom' },
            isLeaf: true,
            pathNode: '1-2',
          },
        ],
      },
    ],
  },
]
