export const menuMock = {
  success: true,
  message: '查询成功',
  code: 200,
  result: {
    allAuth: [
      {
        action: 'online:goGenerateCode',
        describe: '代码生成按钮',
        type: '1',
        status: '1',
      },
      {
        action: 'user:form:phone',
        describe: '手机号禁用',
        type: '2',
        status: '1',
      },
      {
        action: 'user:add',
        describe: '添加用户按钮',
        type: '1',
        status: '1',
      },
    ],
    auth: [
      {
        action: 'user:add',
        describe: '添加用户按钮',
        type: '1',
      },
      {
        action: 'user:form:phone',
        describe: '手机号禁用',
        type: '2',
      },
      {
        action: 'online:goGenerateCode',
        describe: '代码生成按钮',
        type: '1',
      },
    ],
    menu: [
      {
        redirect: null,
        path: '/adminWeb',
        component: 'layouts/RouteView',
        route: '1',
        children: [
          // {
          //   path: '/adminWeb/baseManage',
          //   component: 'adminWeb/baseManage',
          //   route: '1',
          //   meta: {
          //     keepAlive: false,
          //     internalOrExternal: false,
          //     title: '基础数据管理',
          //   },
          //   name: 'data-manage',
          //   id: 'd86f58e7ab516d3bc6bfb1fe',
          // },
          {
            path: '/baseData/schoolManage',
            component: 'baseData/schoolManage/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '学校管理',
            },
            name: 'school-manage',
            id: 'd86f58e7ab516d3bc123wqfe',
          },
          {
            path: '/baseData/classManage',
            component: 'baseData/classManage/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '班级管理',
            },
            name: 'class-manage',
            id: 'd86f58e7ab516d3bc6qw12we',
          },
          {
            path: '/baseData/studentManage',
            component: 'baseData/studentManage/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '学生管理',
            },
            hidden: true,
            name: 'student-manage',
            id: 'd86f58e7ab516d3bc6b12wq1',
          },
          {
            path: '/baseData/import',
            component: 'baseData/import/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '数据导入',
            },
            hidden: true,
            name: 'data-import',
            id: 'd86222e7ab51233bc6qw12we',
          },
          {
            path: '/knowledge/index',
            component: 'knowledge/index',
            route: '1',
            meta: {
              keepAlive: true,
              internalOrExternal: false,
              title: '知识单元管理',
            },
            name: 'knowledge-index',
            id: 'd86f58e7ab516d3bc1232wq1',
          },
          {
            path: '/uploadApp/index',
            component: 'uploadApp/index',
            route: '1',
            meta: {
              keepAlive: true,
              internalOrExternal: false,
              title: 'app更新',
            },
            hidden: true,
            name: 'uploadApp-index',
            id: 'd86f58e211316d3bc1232wq1',
          },
          //   {
          //     path: '/knowledge/learnResource',
          //     component: 'knowledge/learnResource/index',
          //     route: '1',
          //     meta: {
          //       keepAlive: false,
          //       internalOrExternal: false,
          //       title: '学习资源',
          //     },
          //     hidden: true,
          //     name: 'knowledge-learn',
          //     id: 'd86f58233316d3bc1232wq1',
          //   },
          //   {
          //     path: '/knowledge/testResource',
          //     component: 'knowledge/testResource/index',
          //     route: '1',
          //     meta: {
          //       keepAlive: false,
          //       internalOrExternal: false,
          //       title: '试题资源',
          //     },
          //     hidden: true,
          //     name: 'knowledge-test',
          //     id: 'd8233327ab516d3bc1232wq1',
          //   },
        ],

        meta: {
          keepAlive: false,
          internalOrExternal: false,
          icon: 'dashboard',
          title: '基础数据管理',
        },
        name: '',
        id: '717f6bee46f44a3897eca9abd6e',
      },
      {
        redirect: null,
        path: '/examMange',
        component: 'layouts/RouteView',
        route: '1',
        children: [
          {
            path: '/examMange/examAdd/index',
            component: 'examMange/examAdd/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '新增试卷',
            },
            name: 'examMange-examAdd',
            id: 'd86f58234251234323fb1fe',
          },
          {
            path: '/examMange/examEdit/index',
            component: 'examMange/examEdit/index',
            route: '1',
            meta: {
              keepAlive: true,
              internalOrExternal: false,
              title: '试卷编辑',
            },
            hidden: true,
            name: 'examMange-examEdit',
            id: 'd86f58e7as12212bc1232wq1',
          },
          {
            path: '/examMange/examList/index',
            component: 'examMange/examList/index',
            route: '1',
            meta: {
              keepAlive: true,
              internalOrExternal: false,
              title: '试卷列表',
            },
            name: 'examMange-examList',
            id: 'd86f58e7asq12d3bc1232wq1',
          },
        ],
        meta: {
          keepAlive: false,
          internalOrExternal: false,
          icon: 'hdd',
          title: '试卷库管理',
        },
        name: '',
        id: '717fsq112221a3897eca9abd6e',
      },
      {
        redirect: null,
        path: '/accountManage',
        component: 'layouts/RouteView',
        route: '1',
        children: [
          {
            path: '/accountManage/teacher',
            component: 'accountManage/teacher/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '教师管理',
            },
            name: 'accountManage-teacher',
            id: 'd86f58e7ab51234323fb1fe',
          },
          {
            path: '/accountManage/student',
            component: 'accountManage/student/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '学生管理',
            },
            name: 'accountManage-student',
            id: 'd86f58e7ab516d3323fb1fe',
          },
        ],
        meta: {
          keepAlive: false,
          internalOrExternal: false,
          icon: 'user',
          title: '账号管理',
        },
        name: '',
        id: '717fsq1w46f44a3897eca9abd6e',
      },
      {
        redirect: null,
        path: '/system',
        component: 'layouts/RouteView',
        route: '1',
        children: [
          {
            path: '/system/log',
            component: 'system/log/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '日志管理',
            },
            name: 'system-log',
            id: 'd86f58e7a12ssq23fb1fe',
          },
          {
            path: '/system/appConfig',
            component: 'system/appConfig/index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: 'app端设置',
            },
            name: 'system-appConfig',
            id: 'd86f58e7a12s21ssq23fb1fe',
          },
        ],
        meta: {
          keepAlive: false,
          internalOrExternal: false,
          icon: 'setting',
          title: '系统管理',
        },
        name: '',
        id: '717fsq1w46f44a3897eca12wq6e',
      },
      {
        redirect: null,
        path: '/account',
        component: 'layouts/RouteView',
        route: '1',
        hidden: true,
        children: [
          {
            path: '/account/center',
            component: 'account/center/Index',
            route: '1',
            meta: {
              keepAlive: false,
              internalOrExternal: false,
              title: '个人中心',
            },
            name: 'account-center',
            id: 'd86f58e7ab516d3bc6bfb1fe10585f97',
          },
        ],
        meta: {
          keepAlive: false,
          internalOrExternal: false,
          icon: 'user',
          title: '个人页',
        },
        name: 'account',
        id: '717f6bee46f44a3897eca9abd6e2ec44',
      },
    ],
  },
  timestamp: 1624946593208,
}
