export const contentTableConfig = {
  form_item: [
    {
      type: 'input',
      label: '显示信息',
      name: 'message',
      required: true,
    },
    {
      type: 'input',
      label: 'url链接',
      name: 'url',
      required: true,
    },
    {
      type: 'input',
      label: '服务电话',
      name: 'phone',
      required: true,
    },
  ],
  queryParam: {
    message: '福建金创立信息科技发展股份有限公司',
    url:'https://www.baidu.com/',
    phone: '400-8628185',
  },
  form_item_num: [
    {
      type: 'inputNumber',
      label: '自主训练题数',
      name: 'selfTrainQuesCount',
      style: 'width:150px',
      min: 1,
      max: 500,
      required: true,
    },
    {
      type: 'inputNumber',
      label: '顺序训练题数',
      name: 'sortTrainQuesCount',
      style: 'width:150px',
      min: 1,
      max: 500,
      required: true,
    },
    {
      type: 'inputNumber',
      label: '自主模考题数',
      name: 'selfExamQuesCount',
      style: 'width:150px',
      min: 1,
      max: 500,
      required: true,
    },
    {
      type: 'inputNumber',
      label: '自主模考时间(分)',
      name: 'selfExamTime',
      style: 'width:150px',
      min: 1,
      max: 120,
      required: true,
    },
    {
      type: 'inputNumber',
      label: '随机组卷题数',
      name: 'randExamQuesCount',
      style: 'width:150px',
      min: 1,
      max: 500,
      required: true,
    },
    {
      type: 'inputNumber',
      label: '随机组卷时间(分)',
      name: 'randExamTime',
      style: 'width:150px',
      min: 1,
      max: 120,
      required: true,
    },
  ],
  queryParam_num: {
    randExamQuesCount: 10,
    randExamTime: 45,
    selfExamQuesCount: 10,
    selfExamTime: 45,
    selfTrainQuesCount: 10,
    sortTrainQuesCount: 10,
    required: true,
  },
  labelCol: {
    span: 6,
  },
  wrapperCol: {
    span: 18,
  },
}
